import {
  Database,
  DatabaseZap,
  ArrowRightLeft,
  Code,
  Code2,
  FunctionSquare,
  Sparkles,
  CircleCheck,
  CircleX,
  Plug,
  Search,
  Workflow,
  Hash,
  Type,
  Calendar,
  ToggleLeft,
  Braces,
  Fingerprint,
  List,
  FileDigit,
  CircleHelp,
  Key,
  Link,
  Snowflake,
  type LucideIcon,
} from "lucide-react";

export const icons: Record<string, LucideIcon> = {
  // Existing
  source: Database,
  target: DatabaseZap,
  column_mapping: ArrowRightLeft,
  sql_expression: Code,
  ai_generated: Sparkles,
  // Pipeline step types
  sql: Code2,
  code: FunctionSquare,
  ai: Sparkles,
  connection_ok: CircleCheck,
  connection_error: CircleX,
  nav_connections: Plug,
  nav_explorer: Search,
  nav_migrations: Workflow,
  // Type categories
  type_number: Hash,
  type_text: Type,
  type_datetime: Calendar,
  type_boolean: ToggleLeft,
  type_json: Braces,
  type_uuid: Fingerprint,
  type_array: List,
  type_binary: FileDigit,
  type_unknown: CircleHelp,
  // Constraints
  constraint_pk: Key,
  constraint_fk: Link,
  constraint_unique: Snowflake,
};
